/*****************************************************************************
program name :- prims algorithm for minimum spanning tree
authour name :- prashant kumar mishra
roll number :- 2447021
date of creation :- 04-09-2024
date of modification :- 12-09-2024
organization :- National institute of technology patna
******************************************************************************/

#include <stdio.h>
#include<conio.h>

int adj[100][100];
int mst_adj[100][100];
int visited[100];

void main() {
    /* variable declarations */
    int ver;
    int edge;
    int i, j;
    int temp;
    int check;
    int min_src;
    int min_des;
    int min_wgt;
    int mst_wt;

    mst_wt = 0;
    check = 0;
    clrscr();

    /* getting input for the number of vertices */
    printf("\nEnter the number of vertices of the graph: ");
    scanf("%d", &ver);
    printf("\n");

    /* Initialize adjacency matrices with node labels */
    for (i = 0; i <= ver; ++i) {
	for (j = 0; j <= ver; ++j) {
		if(i==0){
			adj[i][j]=j;
			mst_adj[i][j]=j;
		}
		else if(j==0){
			adj[i][j]=i;
			mst_adj[i][j]=i;
		}
		else{
			adj[i][j]=0;
			mst_adj[i][j]=0;
		}

	}
    }

    /* Taking input for the weighted adjacency matrix */
    printf("\n\nEnter the adjacency matrix of the weighted undirected graph:\n");
    for (i = 1; i <= ver; ++i) {
	for (j = 1; j <= i; ++j) {
	    if (i != j) {
		printf("\n Enter the weight of edge between node %d and node %d \n",i,j);
		printf("(enter 0 if there is no edge)\n\t\t: ");

		scanf("%d", &temp);
		adj[i][j] = temp;
		adj[j][i] = temp;
	    }
	}
    }

   
    printf("\n");
    printf("starting prims algorithm for minimum spanning tree \n");

    /* Prim's algorithm to find the minimum spanning tree */
    for (i = 1; i <= ver; ++i) {
	visited[i] = 0;
    }

    i = 1;  // Start with the first vertex
    visited[i] = 1;
    min_src = -1;
    min_des = -1;
    min_wgt = 9999;
    mst_wt = 0;

    while (check < ver - 1) {  // Prim's algorithm loop
	for (i = 1; i <= ver; ++i) {
	    if (visited[i]) {
		for (j = 1; j <= ver; ++j) {
		    if (!visited[j] && adj[i][j] && adj[i][j] < min_wgt) {
			min_wgt = adj[i][j];
			min_src = i;
			min_des = j;
		    }
		}
	    }
	}

	if (min_src != -1 && min_des != -1) {
	    mst_adj[min_src][min_des] = min_wgt;
	    mst_adj[min_des][min_src] = min_wgt;
	    visited[min_des] = 1;
	    mst_wt += min_wgt;
	    min_wgt = 9999;
	    check++;
	}
    }

    /* Display the adjacency matrix of the minimum spanning tree */
    printf("\nThe adjacency matrix of the minimum spanning tree generated by Prim's algorithm:\n");
    for (i = 0; i <= ver; ++i) {
    printf("\n");
	for (j = 0; j <= ver; ++j) {
	    printf("%d\t", mst_adj[i][j]);
	}
	printf("\n");
    }
    printf("\nThe weight of the MST is: %d\n", mst_wt);

   	getch();
}
